name: cloudoc
description: A cross platform flutter app for browsing, saving and editing online documents(word,spreadsheet,slide), including server.
version: 1.0.0
homepage: https://github.com/lindeer/cloudoc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
