/// Flutter icons FontAwesome4
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FontAwesome4
///      fonts:
///       - asset: fonts/FontAwesome4.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FontAwesome4 {
  FontAwesome4._();

  static const _kFontFam = 'FontAwesome4';
  static const String? _kFontPkg = null;

  static const IconData folder_create = IconData(0xf115, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_word = IconData(0xf1c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_excel = IconData(0xf1c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_powerpoint = IconData(0xf1c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_upload = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
