name: cloudoc_server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloudoc:
    path: ..
  path: 1.8.2
  shelf_static: 1.1.1
  shelf: 1.3.2
  shelf_router: 1.1.3
  shelf_cors_headers: 0.1.3
  shelf_multipart: 1.0.0
  any_base: 2.0.0
  uuid: 3.0.6
  http: 0.13.5
  jinja:
    git: https://lindeer:cljs118!@gitee.com/lindeer/jinja.dart.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
